### ISSUE TITLE
Feature request: support JSON formatting for application/vnd.api+json

### ISSUE THREAD

**Issue by jceb** [NTBBloodbath/rest.nvim#61]
JSON:API uses the content-type application/vnd.api+json. It would be great if the `jq` formatting could be applied to it as well.

**Comment by NTBBloodbath** [comment]
Hey, thank you for requesting this, being honest I didn't know about this haha

I think the commit that I pushed a few seconds ago should do the trick, please update and tell me if it works :)

Regards

**Comment by jceb** [comment]
Works great, thanks a lot!

**Comment by manutepowa** [comment]
Why this json is not formatting with jq

Is a drupal JSON:API response 

{"jsonapi":{"version":"1.0","meta":{"links":{"self":{"href":"http:\/\/jsonapi.org\/format\/1.0\/"}}}},"data":[{"type":"node--libros","id":"60892248-28a3-46af-8830-8fc59de00fc7","links":{"self":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros\/60892248-28a3-46af-8830-8fc59de00fc7?resourceVersion=id%3A1"}},"attributes":{"drupal_internal__nid":1,"drupal_internal__vid":1,"langcode":"es","revision_timestamp":"2022-11-26T17:44:55+00:00","revision_log":null,"status":true,"title":"Libro 1","created":"2022-11-26T17:44:40+00:00","changed":"2022-11-26T17:44:55+00:00","promote":false,"sticky":false,"default_langcode":true,"revision_translation_affected":true,"path":{"alias":null,"pid":null,"langcode":"es"},"body":{"value":"\u003Cp\u003Eel libro del rey\u003C\/p\u003E\r\n","format":"basic_html","processed":"\u003Cp\u003Eel libro del rey\u003C\/p\u003E","summary":""}},"relationships":{"node_type":{"data":{"type":"node_type--node_type","id":"d9dc0c1b-5251-475a-b6a6-ac3497c01ddd","meta":{"drupal_internal__target_id":"libros"}},"links":{"related":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros\/60892248-28a3-46af-8830-8fc59de00fc7\/node_type?resourceVersion=id%3A1"},"self":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros\/60892248-28a3-46af-8830-8fc59de00fc7\/relationships\/node_type?resourceVersion=id%3A1"}}},"revision_uid":{"data":{"type":"user--user","id":"ad3ca2c2-08ef-4664-b9ae-f8f956c2cf42","meta":{"drupal_internal__target_id":1}},"links":{"related":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros\/60892248-28a3-46af-8830-8fc59de00fc7\/revision_uid?resourceVersion=id%3A1"},"self":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros\/60892248-28a3-46af-8830-8fc59de00fc7\/relationships\/revision_uid?resourceVersion=id%3A1"}}},"uid":{"data":{"type":"user--user","id":"ad3ca2c2-08ef-4664-b9ae-f8f956c2cf42","meta":{"drupal_internal__target_id":1}},"links":{"related":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros\/60892248-28a3-46af-8830-8fc59de00fc7\/uid?resourceVersion=id%3A1"},"self":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros\/60892248-28a3-46af-8830-8fc59de00fc7\/relationships\/uid?resourceVersion=id%3A1"}}}}}],"links":{"self":{"href":"https:\/\/apiplatform.ddev.site\/api\/node\/libros"}}}

**Comment by peterfication** [comment]
Anyone still having an issue with this, have a look here: https://github.com/rest-nvim/rest.nvim/issues/143#issuecomment-1334828928

**Comment by mtift** [comment]
When I do what is suggested in https://github.com/rest-nvim/rest.nvim/issues/143#issuecomment-1334828928 I get 

```[rest.nvim] WARN: Unrecognized configs found in setup: { "result.behavior.formatters.vnd" }```
